
# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


resources:
- repo: self

stages:
- stage: Deploy
  displayName: Deploy stage
  

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'LosdurosdeDevOpsWebtwitter.frontend-ns'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'Azure for Students(85bc962c-fc3c-40cd-b87c-1c35a1911048)'
              azureResourceGroup: 'resource-group-twitter'
              kubernetesCluster: 'twitter-aks'
              useClusterAdmin: true
              namespace: 'frontend-ns'
              command: 'apply'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
