name: CI/CD

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages

permissions:
  id-token: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
        
      - name: Install Dependencies
        run: npm install
    
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
          login-server: ${{ secrets.ACR_NAME }}

      - name: Build and push Docker images to Azure Container Registry
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_NAME }}/twitter:latest
          build-args: |
            "DATABASE_URL=${{ secrets.DATABASE_URL}}"
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL}}"

      - uses: azure/k8s-set-context@v3
        with:
           method: kubeconfig
           kubeconfig: ${{ secrets.KUBECONFIG_FILE }}
           context: twitter-aks # current-context from kubeconfig is used as default

      - name: Run script file
        run: |
          kubectl delete -f manifests/deployment.yml --namespace=frontend-ns
        shell: bash
      - uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: ${{ secrets.ACR_NAME }}
          container-registry-username: ${{ secrets.AZURE_ACR_USERNAME }}
          container-registry-password: ${{ secrets.AZURE_ACR_PASSWORD }}
          secret-name: demo-k8s-secret

      - uses: Azure/k8s-deploy@v4
        with:
              action: deploy
              namespace: frontend-ns
              manifests: |
                 manifests/deployment.yml
                 manifests/service.yml
              images: |
                 twitterclonecontainerregistry.azurecr.io/twitter:latest
              imagepullsecrets: |
                 demo-k8s-secret
