name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
        
      - name: Install Dependencies
        run: npm install
    
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
          login-server: ${{ secrets.ACR_NAME }}

      - name: Build and push Docker images to Azure Container Registry
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_NAME }}/twitter:latest
          build-args: |
            "DATABASE_URL=${{ secrets.DATABASE_URL}}"
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL}}"
      - name: Azure CD
        uses: Azure/pipelines@v1.2
        with:
          # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
          azure-devops-project-url: https://dev.azure.com/usuario390804/twitter
          # Name of the Azure Pipline to be triggered
          azure-pipeline-name: azure-pipelines
          # Set/Overwrite pipeline variables
          # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
          azure-devops-token: yyjz5ejhil7zw3ftjez7qxamxfe7bkgienty6u5jsunva7s7rhha
          
